baseurl = "https://manueltoral.com"
title = "Manuel Toral"
languageCode = "es"
timeZone = "America/Mexico_City"

canonifyurls = true # Enable to turn relative URLs into absolute.

pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[markup]
defaultMarkdownHandler = "goldmark"

[markup.goldmark.parser.attribute]
block = true

[markup.goldmark.extensions]
table = true
footnote = true

[markup.goldmark.renderer]
unsafe = true

[params]
    author = "Manuel Toral"
    info   = "Gerente de Proyectos de Ciencia de Datos y MLOps"
    description = "Manuel Toral — Líder en Gestión de Proyectos de Ciencia de Datos y MLOps con más de 10 años de experiencia."
    keywords    = "manuel toral, data science, AI/ML, machine learning, public policy, MLOps, R, data visualization"

[[params.social]]
    name = "GitHub"
    weight = 1
    url = "https://github.com/jmtoral"
[[params.social]]
    name = "LinkedIn"
    weight = 2
    url = "https://www.linkedin.com/in/josetoral/"

# Menu links
[[menu.main]]
    name = "Acerca de"
    weight = 1
    url  = "/about/"
[[menu.main]]
    name = "Experiencia"
    weight = 2
    url = "/experience/"
[[menu.main]]
    name = "Blog"
    weight = 3
    url = "/blog/"
[[menu.main]]
    name = "Contacto"
    weight = 4
    url = "/contact/"
